import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Reused variables
const serverDistFolder = dirname(fileURLToPath(import.meta.url));

export const serverConfig = {
  // Server settings
  PORT: Number(process.env['PORT'] || 8080),
  METRICS_PORT: Number(process.env['METRICS_PORT'] || 9090),
  HOST: process.env['HOST'] || 'localhost',
  TRUST_PROXY_HEADERS: process.env['TRUST_PROXY_HEADERS']?.split(',') || [],
  // The API's in-cluster origin for server-side rendering. Unset, the server calls the public URL like the browser.
  API_INTERNAL_URL: process.env['API_INTERNAL_URL'] ? new URL(process.env['API_INTERNAL_URL']).origin : undefined,

  // Connections and probes
  // Above Traefik's 90 s idle timeout for backend connections, so Traefik is the one that closes an idle connection.
  // With Node's 5 s default, Node can close one just as Traefik sends a request on it, which Traefik answers with a 502.
  keepAliveTimeout: 95000,
  // How long the readiness probe waits for the first pre-render of the auto-generated pages
  readyTimeout: 20000,
  // How long an OSRS Wiki call (`SSR_TIMEOUT`) may take during a render before it fails and the browser loads it after
  // hydration. Item pages waited up to 15 s for one; crawlers give up after about 10 s.
  ssrRequestTimeout: 3000,

  // Paths
  serverDistFolder: serverDistFolder,
  browserDistFolder: resolve(serverDistFolder, '../browser'),

  // Cache settings
  pageCache: {
    ttl: 86400000, // 24 hours
    maxSize: 100, // Maximum size of the cache before entries get dropped
  },

  // Pages to auto-generate
  autoGeneratedPages: [
    {
      path: '/',
      interval: 300000, // 5 minute
    },
    {
      path: '/about/changelog',
      interval: 3600000, // 60 minutes
    },
    {
      path: '/about/privacy',
      interval: 86400000, // 24 hours
    },
    {
      path: '/about/terms',
      interval: 86400000, // 24 hours
    },
  ],

  // Static files without a hash in their name that change with every deploy: revalidated on every use
  noCacheStaticFiles: [
    '/manifest.webmanifest',
    '/robots.txt',
    '/sitemap.xml',
    '/sitemap-items.xml',
    '/sitemap-site.xml',
  ],
};
