apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrs-tracker-web
  namespace: default
  labels:
    app: osrs-tracker-web
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: osrs-tracker-web
  template:
    metadata:
      labels:
        app: osrs-tracker-web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: osrs-tracker-web
          image: freekmencke/osrs-tracker-web@sha256:fd20b362ca1c2271410fea2ffe30ab315f0882cc242a3306b9b28e2ad9893b87
          imagePullPolicy: Always
          env:
            - name: HOST
              value: osrs-tracker.freekmencke.com
          ports:
            - containerPort: 8080
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /healthy
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthy
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: osrs-tracker-web-service
  namespace: default
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '9090'
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: osrs-tracker-web
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osrs-tracker-web-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/limit-rps: '50'
    nginx.ingress.kubernetes.io/limit-rpm: '3000'
    nginx.ingress.kubernetes.io/limit-connections: '50'
    nginx.ingress.kubernetes.io/limit-burst-multiplier: '5'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - osrs-tracker.freekmencke.com
      secretName: osrs-tracker-tls
  rules:
    - host: osrs-tracker.freekmencke.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osrs-tracker-web-service
                port:
                  number: 80
