import { AngularNodeAppEngine } from '@angular/ssr/node';
import { type Logger } from '@osrs-tracker/logger';
import { serverConfig } from '../server-config';
import { logger, renderingPage, type WebLogType } from './log';
import { pageCache } from './page-cache';

/**
 * Service for auto-generating pages based on configuration
 */
export class AutoGenerator {
  private intervals: NodeJS.Timeout[] = [];
  private readyTimeout?: NodeJS.Timeout;
  private initialized = false;
  private warm = false;
  private readonly log: Logger;

  /** @param baseLogger Where the `prerender` lines go, stdout unless a spec passes its own */
  constructor(baseLogger: Logger = logger) {
    this.log = baseLogger.child({ type: 'prerender' satisfies WebLogType });
  }

  /**
   * Whether the first render of every page has finished (or failed), or `readyTimeout` passed first, so a slow API
   * can't keep the pod out of the service. The readiness probe waits for it. Always true without `initialize` (the dev
   * server), which pre-renders nothing.
   */
  get ready(): boolean {
    return !this.initialized || this.warm;
  }

  /**
   * Initialize auto-generation of pages based on configuration
   * @param bootstrap Function to bootstrap the Angular application
   */
  initialize(angularApp: AngularNodeAppEngine): void {
    this.log.info('Initializing auto page generation service');

    this.initialized = true;
    this.warm = false;

    // Generate all pages immediately on startup
    void this.generateAllPages(angularApp).then(() => (this.warm = true));
    this.readyTimeout = setTimeout(() => (this.warm = true), serverConfig.readyTimeout);

    // Set up intervals for each page configuration
    serverConfig.autoGeneratedPages.forEach(pageConfig =>
      this.intervals.push(setInterval(() => this.generatePagesForConfig(angularApp, pageConfig), pageConfig.interval)),
    );
  }

  /** Stop all auto-generation intervals */
  shutdown(): void {
    this.log.info('Shutting down auto page generation');
    this.intervals.forEach(interval => clearInterval(interval));
    this.intervals = [];
    clearTimeout(this.readyTimeout);
  }

  /** Generate all pages defined in the configuration */
  private async generateAllPages(angularApp: AngularNodeAppEngine): Promise<void> {
    await Promise.all(
      serverConfig.autoGeneratedPages.map(pageConfig => this.generatePagesForConfig(angularApp, pageConfig)),
    );
  }

  /** Generate pages for a specific configuration */
  private async generatePagesForConfig(
    angularApp: AngularNodeAppEngine,
    pageConfig: (typeof serverConfig.autoGeneratedPages)[number],
  ): Promise<void> {
    try {
      // Pre-render the page, the host must match one of the allowed hosts of the Angular app engine
      const response = await renderingPage(pageConfig.path, () =>
        angularApp.handle(new Request(`https://${serverConfig.HOST}${pageConfig.path}`)),
      );

      // Only cache successful renders, keep serving the previous version otherwise
      if (!response?.ok) {
        this.log.error(`Auto page generation for ${pageConfig.path} failed with status ${response?.status}`);
        return;
      }

      pageCache.set(pageConfig.path, await response.text());
    } catch (err) {
      this.log.error({ error: err }, `Auto page generation for ${pageConfig.path} failed`);
    }
  }
}

// Create a singleton instance
export const autoGenerateService = new AutoGenerator();
