/* eslint-disable no-console */
import { AngularNodeAppEngine } from '@angular/ssr/node';
import { serverConfig } from '../server-config';
import { pageCache } from './page-cache';

/**
 * Service for auto-generating pages based on configuration
 */
export class AutoGenerator {
  private intervals: NodeJS.Timeout[] = [];
  private readyTimeout?: NodeJS.Timeout;

  /**
   * Whether the first render of every page has finished (or failed), or `readyTimeout` passed first, so a slow API
   * can't keep the pod out of the service. The readiness probe waits for it.
   */
  ready = false;

  /**
   * Initialize auto-generation of pages based on configuration
   * @param bootstrap Function to bootstrap the Angular application
   */
  initialize(angularApp: AngularNodeAppEngine): void {
    console.log('Initializing auto page generation service');

    // Generate all pages immediately on startup
    void this.generateAllPages(angularApp).then(() => (this.ready = true));
    this.readyTimeout = setTimeout(() => (this.ready = true), serverConfig.readyTimeout);

    // Set up intervals for each page configuration
    serverConfig.autoGeneratedPages.forEach(pageConfig =>
      this.intervals.push(setInterval(() => this.generatePagesForConfig(angularApp, pageConfig), pageConfig.interval)),
    );
  }

  /** Stop all auto-generation intervals */
  shutdown(): void {
    console.log('Shutting down auto page generation');
    this.intervals.forEach(interval => clearInterval(interval));
    this.intervals = [];
    clearTimeout(this.readyTimeout);
  }

  /** Generate all pages defined in the configuration */
  private async generateAllPages(angularApp: AngularNodeAppEngine): Promise<void> {
    await Promise.all(
      serverConfig.autoGeneratedPages.map(pageConfig => this.generatePagesForConfig(angularApp, pageConfig)),
    );
  }

  /** Generate pages for a specific configuration */
  private async generatePagesForConfig(
    angularApp: AngularNodeAppEngine,
    pageConfig: (typeof serverConfig.autoGeneratedPages)[number],
  ): Promise<void> {
    try {
      // Pre-render the page, the host must match one of the allowed hosts of the Angular app engine
      const response = await angularApp.handle(new Request(`https://${serverConfig.HOST}${pageConfig.path}`));

      // Only cache successful renders, keep serving the previous version otherwise
      if (!response?.ok) {
        console.error(`Auto page generation for ${pageConfig.path} failed with status ${response?.status}`);
        return;
      }

      pageCache.set(pageConfig.path, await response.text());
    } catch (err) {
      console.error(`Auto page generation for ${pageConfig.path} failed:`, err);
    }
  }
}

// Create a singleton instance
export const autoGenerateService = new AutoGenerator();
