// @vitest-environment node
import { AngularNodeAppEngine } from '@angular/ssr/node';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { serverConfig } from '../server-config';
import { AutoGenerator } from './auto-generator';
import { pageCache } from './page-cache';

describe('AutoGenerator', () => {
  const generator = new AutoGenerator();
  const handle = vi.fn<(req: Request) => Promise<Response | null>>();
  const angularApp = { handle } as unknown as AngularNodeAppEngine;
  const home = serverConfig.autoGeneratedPages.find(page => page.path === '/')!;

  /** Starts the generator and waits for the renders it starts on startup */
  async function initialize(): Promise<void> {
    generator.initialize(angularApp);
    await vi.advanceTimersByTimeAsync(0);
  }

  beforeEach(() => {
    vi.useFakeTimers();
    vi.spyOn(console, 'log').mockImplementation(() => undefined);
    vi.spyOn(console, 'error').mockImplementation(() => undefined);
    handle.mockImplementation(async req => new Response(`rendered ${new URL(req.url).pathname}`));
  });
  afterEach(() => {
    generator.shutdown();
    pageCache.clear();
    handle.mockReset();
    vi.restoreAllMocks();
    vi.useRealTimers();
  });

  it('renders every configured page for the configured host on startup', async () => {
    await initialize();

    for (const { path } of serverConfig.autoGeneratedPages) {
      expect(pageCache.get(path)).toBe(`rendered ${path}`);
    }
    expect(new URL(handle.mock.calls[0][0].url).host).toBe(serverConfig.HOST);
  });

  it('re-renders pages on their interval', async () => {
    await initialize();
    handle.mockResolvedValue(new Response('updated'));

    await vi.advanceTimersByTimeAsync(home.interval);

    expect(pageCache.get('/')).toBe('updated');
  });

  it('keeps serving the previous page when a render fails', async () => {
    await initialize();

    handle.mockResolvedValue(new Response('error page', { status: 500 }));
    await vi.advanceTimersByTimeAsync(home.interval);
    expect(pageCache.get('/')).toBe('rendered /');

    handle.mockRejectedValue(new Error('API down'));
    await vi.advanceTimersByTimeAsync(home.interval);
    expect(pageCache.get('/')).toBe('rendered /');
  });

  it('stops rendering after shutdown', async () => {
    await initialize();
    generator.shutdown();
    handle.mockClear();

    await vi.advanceTimersByTimeAsync(home.interval);

    expect(handle).not.toHaveBeenCalled();
  });
});
