const { readdir, readFile, writeFile } = require('fs').promises;

// The skill and activity icons are all shown on every player page, so they're bundled into the XP tracker's JS as data
// URIs (see LOCAL_ICONS) instead of being fetched one by one.
const ICONS_DIR = 'src/assets/icons';
const FOLDERS = ['skills', 'activities'];
const MIME_TYPES = { '.gif': 'image/gif', '.png': 'image/png' };
const OUTPUT = 'src/app/common/directives/icon/local-icons.generated.ts';

(async () => {
  const entries = [];
  for (const folder of FOLDERS) {
    const files = (await readdir(`${ICONS_DIR}/${folder}`)).sort();
    for (const file of files) {
      const mimeType = MIME_TYPES[file.slice(file.lastIndexOf('.'))];
      if (!mimeType) continue;

      const data = await readFile(`${ICONS_DIR}/${folder}/${file}`, 'base64');
      const key = `'/${folder}/${file}':`;
      const value = `'data:${mimeType};base64,${data}',`;
      // the same line breaks prettier would add, so `prettier:ci` passes
      entries.push(key.length + value.length + 3 <= 120 ? `  ${key} ${value}` : `  ${key}\n    ${value}`);
    }
  }

  const source = [
    '// Generated by scripts/icons/local-icons.js (`npm run icons`), do not edit.',
    '',
    '/** Icon data URIs, keyed by their path under `/assets/icons`. */',
    'export const localIcons: Readonly<Record<string, string>> = {',
    ...entries,
    '};',
    '',
  ].join('\n');

  await writeFile(OUTPUT, source, 'utf8');
})();
