import {
  BossEnum,
  BountyHunterEnum,
  ClueScrollsEnum,
  CompetitiveEnum,
  MiniGameEnum,
  RaidEnum,
  SkillEnum,
} from '@osrs-tracker/hiscores';
import { PlayerStatus, PlayerType } from '@osrs-tracker/models';

export const iconMap: Record<string, string> = {
  ['coins']: '/coins.png',
  ['combat']: '/combat.png',
  ['dead']: '/skull.png',

  [PlayerType.Ironman]: '/player_type/ironman.png',
  [PlayerType.Ultimate]: '/player_type/ultimate.png',
  [PlayerType.Hardcore]: '/player_type/hardcore_ironman.png',

  [PlayerStatus.DeIroned]: '/player_type/de_ironman.png',
  [PlayerStatus.DeUltimated]: '/player_type/de_ultimate.png',

  [SkillEnum.Overall]: '/skills/skill_icon_overall1.gif',
  [SkillEnum.Attack]: '/skills/skill_icon_attack1.gif',
  [SkillEnum.Defence]: '/skills/skill_icon_defence1.gif',
  [SkillEnum.Strength]: '/skills/skill_icon_strength1.gif',
  [SkillEnum.Hitpoints]: '/skills/skill_icon_hitpoints1.gif',
  [SkillEnum.Ranged]: '/skills/skill_icon_ranged1.gif',
  [SkillEnum.Prayer]: '/skills/skill_icon_prayer1.gif',
  [SkillEnum.Magic]: '/skills/skill_icon_magic1.gif',
  [SkillEnum.Cooking]: '/skills/skill_icon_cooking1.gif',
  [SkillEnum.Woodcutting]: '/skills/skill_icon_woodcutting1.gif',
  [SkillEnum.Fletching]: '/skills/skill_icon_fletching1.gif',
  [SkillEnum.Fishing]: '/skills/skill_icon_fishing1.gif',
  [SkillEnum.Firemaking]: '/skills/skill_icon_firemaking1.gif',
  [SkillEnum.Crafting]: '/skills/skill_icon_crafting1.gif',
  [SkillEnum.Smithing]: '/skills/skill_icon_smithing1.gif',
  [SkillEnum.Mining]: '/skills/skill_icon_mining1.gif',
  [SkillEnum.Herblore]: '/skills/skill_icon_herblore1.gif',
  [SkillEnum.Agility]: '/skills/skill_icon_agility1.gif',
  [SkillEnum.Thieving]: '/skills/skill_icon_thieving1.gif',
  [SkillEnum.Slayer]: '/skills/skill_icon_slayer1.gif',
  [SkillEnum.Farming]: '/skills/skill_icon_farming1.gif',
  [SkillEnum.Runecraft]: '/skills/skill_icon_runecraft1.gif',
  [SkillEnum.Hunter]: '/skills/skill_icon_hunter1.gif',
  [SkillEnum.Construction]: '/skills/skill_icon_construction1.gif',

  [CompetitiveEnum.LeaguePoints]: '/minigames/game_icon_leaguepoints.png',
  [CompetitiveEnum.PvpArena]: '/minigames/game_icon_pvparenarank.png',
  [CompetitiveEnum.LastManStanding]: '/minigames/game_icon_lmsrank.png',

  [BountyHunterEnum.BountyHunter]: '/minigames/game_icon_bountyhunterhunter.png',
  [BountyHunterEnum.BountyHunterRogues]: '/minigames/game_icon_bountyhunterrogue.png',
  [BountyHunterEnum.BountyHunterLegacy]: '/minigames/game_icon_bountyhunterhunter.png',
  [BountyHunterEnum.BountyHunterLegacyRogues]: '/minigames/game_icon_bountyhunterrogue.png',

  [MiniGameEnum.SoulWarsZeal]: '/minigames/game_icon_soulwarszeal.png',
  [MiniGameEnum.RiftsClosed]: '/minigames/game_icon_riftsclosed.png',
  [MiniGameEnum.ColosseumGlory]: '/minigames/game_icon_colosseumglory.png',
  [MiniGameEnum.CollectionsLogged]: '/minigames/game_icon_collectionslogged.png',

  [ClueScrollsEnum.ClueScrollsAll]: '/cluescrolls/game_icon_cluescrollsall.png',
  [ClueScrollsEnum.ClueScrollsBeginner]: '/cluescrolls/game_icon_cluescrollsbeginner.png',
  [ClueScrollsEnum.ClueScrollsEasy]: '/cluescrolls/game_icon_cluescrollseasy.png',
  [ClueScrollsEnum.ClueScrollsMedium]: '/cluescrolls/game_icon_cluescrollsmedium.png',
  [ClueScrollsEnum.ClueScrollsHard]: '/cluescrolls/game_icon_cluescrollshard.png',
  [ClueScrollsEnum.ClueScrollsElite]: '/cluescrolls/game_icon_cluescrollselite.png',
  [ClueScrollsEnum.ClueScrollsMaster]: '/cluescrolls/game_icon_cluescrollsmaster.png',

  [RaidEnum.ChambersOfXeric]: '/raids/game_icon_chambersofxeric.png',
  [RaidEnum.ChambersOfXericChallengeMode]: '/raids/game_icon_chambersofxericchallengemode.png',
  [RaidEnum.TheGauntlet]: '/raids/game_icon_thegauntlet.png',
  [RaidEnum.TheCorruptedGauntlet]: '/raids/game_icon_thecorruptedgauntlet.png',
  [RaidEnum.TheatreOfBlood]: '/raids/game_icon_theatreofblood.png',
  [RaidEnum.TheatreOfBloodHardMode]: '/raids/game_icon_theatreofbloodhardmode.png',
  [RaidEnum.TombsOfAmascut]: '/raids/game_icon_tombsofamascut.png',
  [RaidEnum.TombsOfAmascutExpertMode]: '/raids/game_icon_tombsofamascutexpertmode.png',

  [BossEnum.AbyssalSire]: '/bosses/game_icon_abyssalsire.png',
  [BossEnum.AlchemicalHydra]: '/bosses/game_icon_alchemicalhydra.png',
  [BossEnum.Artio]: '/bosses/game_icon_artio.png',
  [BossEnum.Amoxliatl]: '/bosses/game_icon_amoxliatl.png',
  [BossEnum.Araxxor]: '/bosses/game_icon_araxxor.png',
  [BossEnum.Bryophyta]: '/bosses/game_icon_bryophyta.png',
  [BossEnum.BarrowsChests]: '/bosses/game_icon_barrowschests.png',
  [BossEnum.Callisto]: '/bosses/game_icon_callisto.png',
  [BossEnum.Calvarion]: '/bosses/game_icon_calvarion.png',
  [BossEnum.Cerberus]: '/bosses/game_icon_cerberus.png',
  [BossEnum.ChaosElemental]: '/bosses/game_icon_chaoselemental.png',
  [BossEnum.ChaosFanatic]: '/bosses/game_icon_chaosfanatic.png',
  [BossEnum.CommanderZilyana]: '/bosses/game_icon_commanderzilyana.png',
  [BossEnum.CorporealBeast]: '/bosses/game_icon_corporealbeast.png',
  [BossEnum.CrazyArchaeologist]: '/bosses/game_icon_crazyarchaeologist.png',
  [BossEnum.DagannothPrime]: '/bosses/game_icon_dagannothprime.png',
  [BossEnum.DagannothRex]: '/bosses/game_icon_dagannothrex.png',
  [BossEnum.DagannothSupreme]: '/bosses/game_icon_dagannothsupreme.png',
  [BossEnum.DerangedArchaeologist]: '/bosses/game_icon_derangedarchaeologist.png',
  [BossEnum.DukeSucellus]: '/bosses/game_icon_dukesucellus.png',
  [BossEnum.GeneralGraardor]: '/bosses/game_icon_generalgraardor.png',
  [BossEnum.GiantMole]: '/bosses/game_icon_giantmole.png',
  [BossEnum.GrotesqueGuardians]: '/bosses/game_icon_grotesqueguardians.png',
  [BossEnum.Hespori]: '/bosses/game_icon_hespori.png',
  [BossEnum.KalphiteQueen]: '/bosses/game_icon_kalphitequeen.png',
  [BossEnum.KingBlackDragon]: '/bosses/game_icon_kingblackdragon.png',
  [BossEnum.Kraken]: '/bosses/game_icon_kraken.png',
  [BossEnum.KreeArra]: '/bosses/game_icon_kreearra.png',
  [BossEnum.KrilTsutsaroth]: '/bosses/game_icon_kriltsutsaroth.png',
  [BossEnum.LunarChests]: '/bosses/game_icon_lunarchests.png',
  [BossEnum.Mimic]: '/bosses/game_icon_mimic.png',
  [BossEnum.Nex]: '/bosses/game_icon_nex.png',
  [BossEnum.Nightmare]: '/bosses/game_icon_nightmare.png',
  [BossEnum.PhosanisNightmare]: '/bosses/game_icon_phosanisnightmare.png',
  [BossEnum.Obor]: '/bosses/game_icon_obor.png',
  [BossEnum.PhantomMuspah]: '/bosses/game_icon_phantommuspah.png',
  [BossEnum.Sarachnis]: '/bosses/game_icon_sarachnis.png',
  [BossEnum.Scorpia]: '/bosses/game_icon_scorpia.png',
  [BossEnum.Scurrius]: '/bosses/game_icon_scurrius.png',
  [BossEnum.Skotizo]: '/bosses/game_icon_skotizo.png',
  [BossEnum.SolHeredit]: '/bosses/game_icon_solheredit.png',
  [BossEnum.Spindel]: '/bosses/game_icon_spindel.png',
  [BossEnum.Tempoross]: '/bosses/game_icon_tempoross.png',
  [BossEnum.TheHueycoatl]: '/bosses/game_icon_thehueycoatl.png',
  [BossEnum.TheLeviathan]: '/bosses/game_icon_theleviathan.png',
  [BossEnum.TheWhisperer]: '/bosses/game_icon_thewhisperer.png',
  [BossEnum.ThermoNuclearSmokeDevil]: '/bosses/game_icon_thermonuclearsmokedevil.png',
  [BossEnum.TzKalZuk]: '/bosses/game_icon_tzkalzuk.png',
  [BossEnum.TzTokJad]: '/bosses/game_icon_tztokjad.png',
  [BossEnum.Vardorvis]: '/bosses/game_icon_vardorvis.png',
  [BossEnum.Venenatis]: '/bosses/game_icon_venenatis.png',
  [BossEnum.Vetion]: '/bosses/game_icon_vetion.png',
  [BossEnum.Vorkath]: '/bosses/game_icon_vorkath.png',
  [BossEnum.Wintertodt]: '/bosses/game_icon_wintertodt.png',
  [BossEnum.Zalcano]: '/bosses/game_icon_zalcano.png',
  [BossEnum.Zulrah]: '/bosses/game_icon_zulrah.png',
};
